### ISSUE TITLE
Problem in using the plugins in tempo2

### ISSUE THREAD

**Issue by parthasarathipal** [demorest/tempo2-conda#3]
I have installed tempo2 from conda-forge

tempo2 -gr basic -h
Looking for /home/partha/workspace/software/anaconda3/envs/gammapy/share/tempo2/plugins//basic_linux-gnu_plug.t2
Graphical Interface: basic
Author:              George Hobbs (May 2004)
Version:             1.0

tempo2 -gr general -h
Looking for /home/partha/workspace/software/anaconda3/envs/gammapy/share/tempo2/plugins//general_linux-gnu_plug.t2
[error]: dlerror() failed while  retrieving address.
dlerror() = (null)

both path for t2 files are same. But it is calling some plugins. and can not call some plugins.
There is a '//' in the path. 
The reason behind the problem is in Linux // does not make any problem.
In python when the path is defined as string then '//' and '/' are different.

Please correct this in your source code.

**Comment by demorest** [comment]
Hi, thanks for the report.

The `//` is not the problem.  tempo2 has two types of plugin, "graphical" and "output".  Since general is an output plugin you use `-output` rather than `-gr`.  ie, `tempo2 -output general`.

Also note that this repository is no longer active.  Issues with the tempo2 code itself should be reported at https://bitbucket.org/psrsoft/tempo2/src rather than here.  Issues specific to conda-forge should go to  https://github.com/conda-forge/tempo2-feedstock/
